#!/usr/bin/env python3
"""
Daily Morning Briefing Generator

Runs every morning to create a summary of:
- Pending tasks
- Recent activity
- Upcoming deadlines
- System health
"""

import json
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List


class DailyBriefing:
    """Generate daily morning briefing"""

    def __init__(self, vault_path: str = "AI_Employee_Vault"):
        self.vault_path = Path(vault_path)
        self.needs_action = self.vault_path / "Needs_Action"
        self.done = self.vault_path / "Done"
        self.logs = self.vault_path / "Logs"
        self.dashboard = self.vault_path / "Dashboard.md"

    def count_pending_tasks(self) -> Dict[str, int]:
        """Count pending tasks by type"""
        counts = {
            "email": 0,
            "whatsapp": 0,
            "approval": 0,
            "alert": 0,
            "other": 0
        }

        for file in self.needs_action.glob("*.md"):
            name = file.name.upper()
            if "EMAIL" in name:
                counts["email"] += 1
            elif "WHATSAPP" in name:
                counts["whatsapp"] += 1
            elif "APPROVAL" in name:
                counts["approval"] += 1
            elif "ALERT" in name:
                counts["alert"] += 1
            else:
                counts["other"] += 1

        return counts

    def get_yesterday_activity(self) -> Dict:
        """Get activity from yesterday's logs"""
        yesterday = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
        log_file = self.logs / f"{yesterday}.json"

        if not log_file.exists():
            return {"total": 0, "by_type": {}}

        try:
            with open(log_file, 'r') as f:
                logs = json.load(f)

            by_type = {}
            for entry in logs:
                action_type = entry.get("type", "unknown")
                by_type[action_type] = by_type.get(action_type, 0) + 1

            return {
                "total": len(logs),
                "by_type": by_type
            }
        except:
            return {"total": 0, "by_type": {}}

    def count_completed_yesterday(self) -> int:
        """Count files completed yesterday"""
        yesterday = datetime.now() - timedelta(days=1)
        count = 0

        for file in self.done.glob("*.md"):
            if file.stat().st_mtime > yesterday.timestamp():
                count += 1

        return count

    def generate_briefing(self) -> str:
        """Generate the briefing content"""
        now = datetime.now()
        pending = self.count_pending_tasks()
        yesterday = self.get_yesterday_activity()
        completed = self.count_completed_yesterday()

        briefing = f"""# Daily Morning Briefing
**Generated**: {now.strftime("%Y-%m-%d %H:%M:%S")}

---

## 📊 System Status

**Watchers**: Running ✓
**Last Check**: {now.strftime("%H:%M:%S")}

## 📥 Pending Tasks ({sum(pending.values())} total)

"""

        if sum(pending.values()) > 0:
            for task_type, count in pending.items():
                if count > 0:
                    icon = {
                        "email": "📧",
                        "whatsapp": "📱",
                        "approval": "✋",
                        "alert": "⚠️",
                        "other": "📄"
                    }.get(task_type, "📄")
                    briefing += f"- {icon} **{task_type.title()}**: {count}\n"
        else:
            briefing += "✅ No pending tasks\n"

        briefing += f"""
## 📈 Yesterday's Activity

- **Total Actions**: {yesterday['total']}
- **Tasks Completed**: {completed}

"""

        if yesterday['by_type']:
            briefing += "**Breakdown**:\n"
            for action_type, count in yesterday['by_type'].items():
                briefing += f"- {action_type}: {count}\n"

        briefing += f"""
## 🎯 Today's Focus

"""

        # Add priority items
        priority_files = list(self.needs_action.glob("*URGENT*.md"))
        if priority_files:
            briefing += "**Priority Items**:\n"
            for file in priority_files[:5]:
                briefing += f"- {file.stem}\n"
        else:
            briefing += "No urgent items\n"

        briefing += """
---
*Generated by AI Employee Daily Briefing*
"""

        return briefing

    def save_briefing(self, content: str):
        """Save briefing to vault"""
        briefing_dir = self.vault_path / "Briefings"
        briefing_dir.mkdir(exist_ok=True)

        filename = f"BRIEFING_{datetime.now().strftime('%Y-%m-%d')}.md"
        filepath = briefing_dir / filename

        filepath.write_text(content)
        print(f"✓ Briefing saved: {filepath}")

        # Also update Dashboard
        if self.dashboard.exists():
            dashboard_content = self.dashboard.read_text()

            # Add briefing summary to top
            summary = f"\n## 📋 Today's Briefing ({datetime.now().strftime('%Y-%m-%d')})\n"
            summary += f"See: [Briefings/{filename}](Briefings/{filename})\n\n"

            self.dashboard.write_text(summary + dashboard_content)
            print(f"✓ Dashboard updated")


def main():
    """Main entry point"""
    print("=" * 70)
    print("📋 Generating Daily Morning Briefing")
    print("=" * 70)

    briefing = DailyBriefing()
    content = briefing.generate_briefing()
    briefing.save_briefing(content)

    print("\n✅ Daily briefing complete")


if __name__ == "__main__":
    main()
