#!/bin/bash
# PM2 Boot Startup Setup
# This script provides instructions for enabling PM2 to start on system boot

echo "============================================================"
echo "PM2 Boot Startup Configuration"
echo "============================================================"
echo ""
echo "To enable PM2 services to start automatically on system boot,"
echo "you need to run the following command with sudo privileges:"
echo ""
echo "COMMAND TO RUN:"
echo "---------------"
cat << 'EOF'
sudo env PATH=$PATH:/home/bilal-amir/.nvm/versions/node/v20.19.6/bin /home/bilal-amir/.nvm/versions/node/v20.19.6/lib/node_modules/pm2/bin/pm2 startup systemd -u bilal-amir --hp /home/bilal-amir
EOF
echo ""
echo "============================================================"
echo "What This Does:"
echo "============================================================"
echo "- Creates a systemd service for PM2"
echo "- Configures PM2 to start on system boot"
echo "- Restores saved process list automatically"
echo "- Ensures 24/7 operation even after reboots"
echo ""
echo "============================================================"
echo "After Running the Command:"
echo "============================================================"
echo "1. PM2 will be registered as a system service"
echo "2. Services will auto-start on boot"
echo "3. Current process list is already saved (pm2 save was run)"
echo ""
echo "============================================================"
echo "To Verify Setup:"
echo "============================================================"
echo "After reboot, check services with:"
echo "  pm2 status"
echo ""
echo "============================================================"
echo "Note: This is OPTIONAL"
echo "============================================================"
echo "The automation system works without this."
echo "This just adds boot persistence for convenience."
echo ""
